# Generated by Django 5.0.6 on 2024-05-31 10:50

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('first_name'), '+', models.F('last_name')), output_field=models.CharField(max_length=200))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
