# Generated by Django 5.0.6 on 2024-06-03 13:20

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('first_name'), '+', models.Value(' ')), '+', models.F('last_name')), output_field=models.CharField(max_length=200)),
        ),
    ]
