# Generated by Django 5.0.6 on 2024-06-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='authentication.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='user_friend_unique_constraint', violation_error_message='User and friend are the same'),
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('friend')), _negated=True), name='prevent_self_friendship', violation_error_message='User and friend are the same'),
        ),
    ]
