# Generated by Django 5.0.6 on 2024-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('friend_request', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='user_friend_unique_constraint', violation_error_message='User and friend are the same'),
        ),
    ]
