# Generated by Django 5.0.6 on 2024-06-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('friend_request', '0002_friends_user_friend_unique_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('friend')), _negated=True), name='prevent_self_friendship'),
        ),
    ]
