# Generated by Django 5.0.6 on 2024-06-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('friend_request', '0003_friends_prevent_self_friendship'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friends',
            name='prevent_self_friendship',
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('friend')), _negated=True), name='prevent_self_friendship', violation_error_message='User and friend are the same'),
        ),
    ]
